#!/bin/bash

sudo cp ./conf/etc/nginx/nginx.conf /etc/nginx/nginx.conf
sudo cp ./conf/etc/mysql/my.cnf /etc/mysql/my.cnf
sudo cp ./conf/etc/systemd/system/isuda.perl.service /etc/systemd/system/isuda.perl.service
sudo cp ./conf/etc/systemd/system/isutar.perl.service /etc/systemd/system/isutar.perl.service
./carton-install
./restart
